{% set name = "neptune-notebooks" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neptune-ai/neptune-notebooks/archive/{{ version }}.tar.gz
  sha256: 9fd31e91029a9470227bd6f23f358a2f8e763614d59d2434dfbda6d476e2a0e5

build:
  noarch: python
  number: 0
  entry_points:
    - neptune_notebooks = neptune_notebooks_plugin:notebook
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - nodejs
    - openjdk
  run:
    - python >=3.6
    - click >=7.0
    - future >=0.17.1
    - neptune-client >=0.4.92
    - notebook >=4.3.0
    - path.py

test:
  imports:
    - neptune_notebooks

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune's integration with Jupiter and JupiterLab notebooks
  doc_url: https://docs.neptune.ai
  dev_url: https://github.com/neptune-ai/neptune-notebooks

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - shnela
    - pitercl
    - Raalsky
