{% set name = "neptune-notebooks" %}
{% set version = "0.0.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/neptune-ai/neptune-notebooks/archive/{{ version }}.tar.gz"
  sha256: 1403069f5cbbe52acdf596f5e56ad8fadfc99ebf094c66c43c84a3b212db9ef5

build:
  noarch: python
  number: 0
  entry_points:
    - neptune_notebooks = neptune_notebooks_plugin:notebook
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - click >=7.0
    - future >=0.17.1
    - neptune-client >=0.4.92
    - notebook >=4.3.0
    - path.py

test:
  imports:
    - neptune_notebooks
    - tests.neptune_notebooks
    - tests.neptune_notebooks_plugin

about:
  home: "https://neptune.ai/"
  license: Apache-2.0
  license_family: "APACHE"
  license_file: "LICENSE"
  summary: "Neptune's integration with Jupiter and JupiterLab notebooks"
  doc_url: "https://docs.neptune.ai"
  dev_url: "https://github.com/neptune-ai/neptune-notebooks"

extra:
  recipe-maintainers:
    - szymon-kuklewicz
    - aniezurawski
    - hubertjaworskineptune
    - pitercl
